apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-diagnosis-agent
  namespace: k8s-diagnosis-system
spec:
  ingressClassName: nginx
  rules:
    - host: k8s-diagnosis.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k8s-diagnosis-agent
                port:
                  name: http
